//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.ValidationRules.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugin.ValidationRules.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card is not valid..
        /// </summary>
        internal static string CreditCardRuleMessage {
            get {
                return ResourceManager.GetString("CreditCardRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        internal static string EmailRuleMessage {
            get {
                return ResourceManager.GetString("EmailRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be empty..
        /// </summary>
        internal static string EmptyRuleMessage {
            get {
                return ResourceManager.GetString("EmptyRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid..
        /// </summary>
        internal static string EnumRuleMessage {
            get {
                return ResourceManager.GetString("EnumRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be equal..
        /// </summary>
        internal static string EqualRuleMessage {
            get {
                return ResourceManager.GetString("EqualRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value length is not the same..
        /// </summary>
        internal static string ExactLengthRuleMessage {
            get {
                return ResourceManager.GetString("ExactLengthRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than or equal to the min length..
        /// </summary>
        internal static string GreaterThanOrEqualRuleMessage {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than the min length..
        /// </summary>
        internal static string GreaterThanRuleMessage {
            get {
                return ResourceManager.GetString("GreaterThanRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not greater than or equal to the min length and less than or equal to the max length..
        /// </summary>
        internal static string InclusiveBetweenRuleMessage {
            get {
                return ResourceManager.GetString("InclusiveBetweenRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max should be larger than min..
        /// </summary>
        internal static string InvalidMaximumMessage {
            get {
                return ResourceManager.GetString("InvalidMaximumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To should be larger than from..
        /// </summary>
        internal static string InvalidToMessage {
            get {
                return ResourceManager.GetString("InvalidToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value length is invalid..
        /// </summary>
        internal static string LengthRuleMessage {
            get {
                return ResourceManager.GetString("LengthRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than or equal to max lentgh..
        /// </summary>
        internal static string LessThanOrEqualRuleMessage {
            get {
                return ResourceManager.GetString("LessThanOrEqualRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not less than the max length..
        /// </summary>
        internal static string LessThanRuleMessage {
            get {
                return ResourceManager.GetString("LessThanRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value length is greater than the max length..
        /// </summary>
        internal static string MaxLengthRuleMessage {
            get {
                return ResourceManager.GetString("MaxLengthRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value length is less than the min length..
        /// </summary>
        internal static string MinimumLengthRuleMessage {
            get {
                return ResourceManager.GetString("MinimumLengthRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should not be empty..
        /// </summary>
        internal static string NotEmptyRuleMessage {
            get {
                return ResourceManager.GetString("NotEmptyRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should not be equal..
        /// </summary>
        internal static string NotEqualRuleMessage {
            get {
                return ResourceManager.GetString("NotEqualRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should not be null..
        /// </summary>
        internal static string NotNullRuleMessage {
            get {
                return ResourceManager.GetString("NotNullRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be null..
        /// </summary>
        internal static string NullRuleMessage {
            get {
                return ResourceManager.GetString("NullRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not valid..
        /// </summary>
        internal static string RegularExpressionRuleMessage {
            get {
                return ResourceManager.GetString("RegularExpressionRuleMessage", resourceCulture);
            }
        }
    }
}
